language: node_js
node_js:
  - "12.14"

deploy:
  provider: npm
  email: kostikkisil@gmail.com
  api_key:
    secure: "GAdO6qJKXUK1NAvxzqKZoODpsP8cF5YtDbgO8jm306wjViDJWY1LOWZWWXZ3kv4UaHcOsA2Vq2Y3iCqlP9Yr07BJuXwCUgt+lqyDpJV8lA8Lu/5jq0dnT21pHScl2lVttrPvKzDrMMoPXcp85FyNov2bWzV2tQS2nfU0lCcfU0Fwtq8NbdXaOalAQokrM/GpzkdiRoriBdvn3gt3Guhw4Dzuw4odRN7xUxK3nngMeDMWi9+/7o89O79xe0hdR+f94WXf3Q0l0F0YaIoO5pg7NGgqA/9Autt4ilV0USHsTvDwELl1LzGOPPkKFIeTA4zoTStVI6YFvsS3ceczOhh3BXKOSU/S42XkmU4WfE3Yypf/n4sTnAyvbY7O0AnqJoKwEA/JhOLj46Fn0a/I5kNg6L0GVyWxQ2fcbwjTuXr63nOVOH50KNbD6/olNR+zJz0nu0xtosibnnu1hXYjMOA7pRHPIU1RRhNT1emmgJccCLmCoCuomy3cJGM609hKU/PyV1AzulbJYHePwYhFoLngmA5DFcU9CmFKVhOKyaG0h6sAQQmVLQif9Em1nDY/LyPRJS7bFs72rU8+ejxvAN4JWxOUBNneLGKiRIQNTPrUCxMGs9bNXKz/bxFlt1Y64oplGSR1E1KKeOB5pDodUBk0LSDSnLEAd23yjSfZmwO+E90="
